    - name: Compilar o arquivo .XEX
      run: make

    - name: Disponibilizar arquivo para Download
      uses: actions/upload-artifact@v4
      with:
        name: dashboard-xbox360
        path: xbox_dash.xex
