name: Gerar Skin XMB Aurora

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar arquivos do repositorio
      uses: actions/checkout@v4

    - name: Instalar ferramenta de compressão zip
      run: sudo apt-get install -y zip

    - name: Empacotar Skin para o formato do Xbox 360
      run: |
        # O console lê o layout comprimido. Vamos renomear para .xzp
        zip -r XMB_PS3.zip skin.xml
        mv XMB_PS3.zip XMB_PS3.xzp

    - name: Disponibilizar Skin para Download
      uses: actions/upload-artifact@v4
      with:
        name: skin-ps3-xbox360
        path: XMB_PS3.xzp
